#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

echo "$1" | grep -F "/" > /dev/null &&  mkdir -p "$(dirname "$1")" || true

if [[ "$1" == "svg" ]] && [ "$#" -eq 1 ]; then
    cat "/dev/stdin" | dot -T svg | awk '/<svg/ { PRINT=1; }; PRINT==1 { print $0; }' | tr -d '\n'
    exit 0
fi

cat "/dev/stdin" | dot -T ${1##*.} -o "$1"

if [ "$#" -gt 1 ]; then
    echo "![$2]($1)"
    exit
fi
echo "![$1]($1)"
