#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

echo "$1" | grep -F "/" > /dev/null &&  mkdir "$(dirname "$1")" || true

cat "/dev/stdin" | erd -o "$1"

if [ "$#" -gt 1 ]; then
    echo "![$2]($1)"
    exit
fi
echo "![$1]($1)"
