#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

function post {
    if [[ "$1"  == "svg" ]]; then
        awk '/<svg/ { PRINT=1; }; PRINT==1 { print $0; }' | tr -d '\n'
        exit
    fi
    cat
}

echo "$1" | grep -F "/" > /dev/null &&  mkdir -p "$(dirname "$1")" || true

if [ "$#" -lt 2 ]; then
    cat "/dev/stdin" | dot -T "$1" | post "$1"
    exit 0
fi

mkdir -p "$(dirname "$2")"

cat "/dev/stdin" | dot -T "$1" | post "$1" > "$2"

echo "![$1]($2)"
