#!/bin/bash

show_help() {
    echo "$1 [-h] [-m] [-b INTEGER]"
    echo ""
    echo "-h = Help"
    echo "-m = output Markdown instead of HTML"
    echo "-b = the number to add to headers (could be negative)"
    echo ""
    exit 0
}

MARKDOWN=0
BEHEAD=0

while getopts "hmb:" opt; do
    case "$opt" in
        m)
            MARKDOWN=1
            ;;
        h)
            show_help
            exit 0
            ;;
        b)  BEHEAD="$OPTARG"
            ;;
    esac
done
shift $(( OPTIND - 1 ))


if [ "$#" -gt 0 ]; then
    CURRENT="$(cat "$1")"
else
    CURRENT="$(cat "/dev/stdin")"
fi

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(dirname "$0")"

while echo "$CURRENT" | grep '```.*#' > /dev/null ; do
    CURRENT="$(echo "$CURRENT" | node "$SCRIPT_DIR/remark-copy-code-meta-hash-down.js")"
done


while echo "$CURRENT" | grep '``` *unixpipe' > /dev/null ; do
    CURRENT="$(echo "$CURRENT" | node "$SCRIPT_DIR/remark-unixpipe.js")"
done

CURRENT="$(echo "$CURRENT" | node "$SCRIPT_DIR/code-import.js")"
CURRENT="$(echo "$CURRENT" | node $SCRIPT_DIR/behead.js "$BEHEAD")"

if [ "$MARKDOWN" -gt 0 ]; then
    echo "$CURRENT"
    exit 0
fi

echo "$CURRENT" | node "$SCRIPT_DIR/rehype.js"
echo ""
