#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

CURRENT="$(cat "/dev/stdin")"
SCRIPT_DIR="$(dirname "$0")"

while echo "$CURRENT" | grep '```.*#' > /dev/null ; do
    CURRENT="$(echo "$CURRENT" | node "$SCRIPT_DIR/remark-copy-code-meta-hash-up.js")"
done


while echo "$CURRENT" | grep '``` *unixpipe' > /dev/null ; do
    CURRENT="$(echo "$CURRENT" | node "$SCRIPT_DIR/remark-unixpipe.js")"
done

if [ "$#" -gt "0" ] && [ "$1" == "--as-markdown" ]; then
    echo "$CURRENT"
    exit 0
fi
echo "$CURRENT" | node "$SCRIPT_DIR/rehype.js"
